TrainingArguments:
  output_dir: pegasus-samsum
  num_train_epochs: 3
  warmup_steps: 1000
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  weight_decay: 0.01
  logging_steps: 50
  evaluation_strategy: steps
  eval_steps: 200
  save_steps: 200
  gradient_accumulation_steps: 8
  learning_rate: 5e-5
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: eval_rouge1
  greater_is_better: true